# Generated by Django 6.1.1 on 2026-09-16 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_cuisine', models.CharField(max_length=100)),
                ('disliked_cuisine', models.CharField(blank=True, max_length=100)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=100)),
                ('favorite_food', models.CharField(blank=True, max_length=100)),
                ('preferred_price_range', models.CharField(max_length=20)),
                ('preferred_dining_atmosphere', models.CharField(max_length=100)),
                ('willing_to_try_new_foods', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
