# Generated by Django 6.1.1 on 2026-10-05 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_foodpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distance_preference',
            field=models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_prompt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
